## dataset
dataset: "GRCh38-freeze1"
## experiments
exp: "vg/linear cactus/f1g-90-mc-jul7 cactus/f1g-90-mc-jul7-gaffix cactus/f1g-90-mc-jul7/CHM13-freeze1 minigraph/f1g-90/GRCh38-freeze1/paths minigraph/f1g-90/CHM13-freeze1/paths vg/linear/CHM13-freeze1"
## alias for reports
report_alias: 'GRCH38.linear GRCh38.minigraph.cactus.jul7 GRCh38.minigraph.cactus.jul7.gaffix CHM13.minigraph.cactus.jul7 GRCh38.minigraph CHM13.minigraph CHM13.linear'
## s3 root bucket
s3root: 'vg-k8s/vgamb/wg'
## vg mapping
mapper: "giraffe"
min_k: 29
min_w: 11
cover_n: 16
map_cores: 16
## other mapping
mapper_lr: "ga"
## regions to visualize
viz_bed: "pangenome-viz-regions-wg.bed"
## input s3 links
s3_input_links: 'input.graphs.s3.links.csv'
## output
html_out: "evaluation-report-wg.html"
viz_html_out: "visualization-report-wg.html"
