## dataset
dataset: "hpp60"
chr: "chr20"
## experiments
exp: "vg/linear cactus/minimap2-star-no-secondary-2020-09-04-glenn-debug cactus/minigraph-2020-10-28-u1-dna-brnn cactus/minigraph-2020-10-28-dna-brnn-nu1-b100k-q5-s500-caf cactus/minigraph-2020-10-28-dna-brnn-nu1-b100k-q5-s1000-caf cactus/minimap-poa minigraph/L50-l50k paftools/asm20-L10k-l1k"
## s3 root bucket
s3root: 'vg-k8s/vgamb/chr20'
## vg mapping
mapper: "giraffe"
min_k: 39
min_w: 15
cover_n: 16
gbwt_auto: true
map_cores: 8
## other mapping
mapper_lr: "ga"
## regions to visualize
viz_bed: "pangenome-viz-regions.bed"
## input s3 links
s3_input_links: 'input.graphs.s3.links.csv'
## output
html_out: "evaluation-report-cactus.html"
viz_html_out: "visualization-report-cactus.html"
