## dataset
dataset: "GRCh38-freeze1"
## experiments
exp: "vg/linear cactus/f1g-90-mc-aug11/GRCh38-freeze1/45k cactus/f1g-90-mc-aug11/GRCh38-freeze1/64k cactus/f1g-90-mc-aug11/GRCh38-freeze1 cactus/f1g-90-mc-aug11-clip-d2-m1000 minigraph/f1g-90/GRCh38-freeze1/paths vg/linear/CHM13-freeze1 cactus/f1g-90-mc-aug11/CHM13-freeze1 minigraph/f1g-90/CHM13-freeze1/paths cactus/f1g-90-mc-aug11-D10m/GRCh38-freeze1 cactus/f1g-90-mc-aug11-D10m/CHM13-freeze1 cactus/f1g-90-mc-aug11-D10m-clip-d9-m1000/GRCh38-freeze1 cactus/f1g-90-mc-aug11-D10m-clip-d9-m1000/CHM13-freeze1"
## alias for reports
report_alias: 'GRCH38.linear GRCh38.minigraph.cactus.map.pruneK45 GRCh38.minigraph.cactus.map.pruneK64 GRCh38.minigraph.cactus GRCh38.minigraph.cactus.clipped GRCh38.minigraph CHM13.linear CHM13.minigraph.cactus.jul7 CHM13.minigraph GRCh38.minigraph.cactus.D10m CHM13.minigraph.cactus.D10m GRCh38.minigraph.cactus.D10m.clipped CHM13.minigraph.cactus.D10m.clipped'
## s3 root bucket
s3root: 'vg-k8s/vgamb/wg'
## vg mapping
mapper: "giraffe vgmap vgmap giraffe giraffe giraffe giraffe giraffe giraffe"
min_k: 29
min_w: 11
cover_n: 16
map_cores: 32
## other mapping
mapper_lr: "ga"
## vg genotyping
call_a: false
pack_q: 5
pack_s: 0
## regions to visualize
viz_bed: "pangenome-viz-regions-wg.bed"
## input s3 links
s3_input_links: 'input.graphs.s3.links.csv'
## output
html_out: "evaluation-report-wg.html"
viz_html_out: "visualization-report-wg.html"
