## dataset
dataset: "hpp60"
chr: "chr2"
## experiments
exp: "vg/linear minigraph/L50-l50k cactus/minigraph-softmasked-hg38-overlapfix"
## s3 root bucket
s3root: 'vg-k8s/vgamb/chr2'
## vg mapping
mapper: "giraffe"
min_k: 29
min_w: 11
cover_n: 16
gbwt_auto: true
map_cores: 8
## other mapping
mapper_lr: "ga"
## regions to visualize
viz_bed: "pangenome-viz-regions.bed"
## input s3 links
s3_input_links: 'input.graphs.s3.links.csv'
## output
html_out: "evaluation-report.html"
viz_html_out: "visualization-report.html"
